services:
  ext-stat-plugin-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ext-stat-plugin-test
    volumes:
      - .:/app

  db:
    image: postgres:18.4
    container_name: ext-stat-plugin-test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ext-stat-plugin-test-migrations
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://test_user:test_password@db:5432/test_db
    command: alembic upgrade head